App\Entity\Categorias:
  properties:
    categoria:
      - NotBlank:
          message: 'El campo Categoria es Obligatorio'
      - Length:
          min: 2
          max: 100
          minMessage: 'Almenos 2 caracteres'
          maxMessage: 'Maximo 100 caracteres'
